### ISSUE TITLE
Navigation works, Find Usages doesn't

### ISSUE THREAD

**Issue by donnerpeter** [maximehamm/i18n#1]
I have a TypeScript project with i18next, and the navigation from `i18next.t('key')` to the resource file works, but Find Usages doesn't, when invoked on the property in the resource file.

**Comment by maximehamm** [comment]
Hello Peter
I18N is bot managing references and usages... this is part of IntelliJ Idea itself or may be the resource bundle editor plugin.
Sorry, I can't help much more here !
